// ── send-sms.js ─────────────────────────────────────────────────────────────
// Sends a HIPAA signing link via Twilio SMS to the patient's phone number.
//
// Netlify Environment Variables required (set in Netlify dashboard only):
//   TWILIO_ACCOUNT_SID
//   TWILIO_AUTH_TOKEN
//   TWILIO_FROM_NUMBER
//   PORTAL_URL
// ─────────────────────────────────────────────────────────────────────────────

exports.handler = async (event) => {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json',
  };

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers, body: '' };
  }

  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers, body: JSON.stringify({ error: 'Method not allowed' }) };
  }

  let body;
  try {
    body = JSON.parse(event.body);
  } catch {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'Invalid JSON body' }) };
  }

  const { toPhone, patientName, caseRef, signingToken } = body;

  if (!toPhone) {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'toPhone is required' }) };
  }

  // ── Env vars ───────────────────────────────────────────────────────────────
  const accountSid  = process.env.TWILIO_ACCOUNT_SID;
  const authToken   = process.env.TWILIO_AUTH_TOKEN;
  const fromNumber  = process.env.TWILIO_FROM_NUMBER || '+17177561092';
  const portalUrl   = process.env.PORTAL_URL || 'https://glowing-pavlova-dea557.netlify.app';

  if (!accountSid || !authToken) {
    console.error('Missing Twilio credentials in environment');
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        success: false,
        fallback: true,
        message: 'Twilio credentials not configured. Add TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN to Netlify environment variables.',
      }),
    };
  }

  // ── Build signing link ─────────────────────────────────────────────────────
  // Token is a short-lived URL param — in production this would be a signed JWT
  // stored server-side. For now we pass the token generated by the front end.
  const token = signingToken || Math.random().toString(36).substring(2) + Date.now().toString(36);
  const signingUrl = `${portalUrl}/sign.html?token=${token}`;

  // ── Format phone number ────────────────────────────────────────────────────
  // Strip non-digits, add +1 if no country code
  let phone = toPhone.replace(/\D/g, '');
  if (phone.length === 10) phone = '1' + phone;
  if (!phone.startsWith('+')) phone = '+' + phone;

  // ── SMS message ────────────────────────────────────────────────────────────
  const nameStr = patientName ? `, ${patientName.split(' ')[0]}` : '';
  const caseStr = caseRef ? ` (Ref: ${caseRef})` : '';
  const messageBody =
    `Marzzacco Niven & Associates${caseStr} has requested your HIPAA authorization for medical records. ` +
    `Please review and sign here:\n\n${signingUrl}\n\n` +
    `This link expires in 48 hours. Reply STOP to opt out.`;

  // ── Send via Twilio REST API ───────────────────────────────────────────────
  try {
    const twilioUrl = `https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`;

    const params = new URLSearchParams();
    params.append('To',   phone);
    params.append('From', fromNumber);
    params.append('Body', messageBody);

    const credentials = Buffer.from(`${accountSid}:${authToken}`).toString('base64');

    const response = await fetch(twilioUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${credentials}`,
        'Content-Type':  'application/x-www-form-urlencoded',
      },
      body: params.toString(),
    });

    const result = await response.json();

    if (response.ok && result.sid) {
      console.log(`SMS sent to ${phone} — SID: ${result.sid}`);
      return {
        statusCode: 200,
        headers,
        body: JSON.stringify({
          success:    true,
          messageSid: result.sid,
          to:         phone,
          signingUrl,
          token,
        }),
      };
    } else {
      console.error('Twilio error:', result);
      return {
        statusCode: 200,
        headers,
        body: JSON.stringify({
          success: false,
          error:   result.message || result.code || 'Twilio send failed',
          details: result,
        }),
      };
    }
  } catch (err) {
    console.error('send-sms fetch error:', err);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ success: false, error: err.message }),
    };
  }
};
